defaults:
  - _self_
  - wandb: private.yaml
  - augmentations: linear.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-linear"
finetune: False # perform finetune or linear-probbing
pretrain:
  method: "byol"
  # ckpt: "trained_models/byol/ehzlcvt1/byol-ehzlcvt1-ep=99.ckpt"
  ckpt: "trained_models/byol/q7jeim0r/byol-symmetric-q7jeim0r-ep=99.ckpt" # lr = 0.5
  # ckpt: "trained_models/byol/jip4b0nc/byol-symmetric-jip4b0nc-ep=99.ckpt" # lr = 0.25
  # ckpt: "trained_models/byol/vdq7vn61/byol-symmetric-vdq7vn61-ep=99.ckpt" # lr = 0.5, 2048
  ckpt_key: "momentum_backbone"
backbone:
  name: "resnet18"
loss_fn: 
  name: "ce" # choose from [ce, focal, label_smoothing_ce, soft_target_ce]
data:
  dataset: isic2016
  data_path: "data/pretrain/images"
  train_label: "data/pretrain/ISIC_2016_train.csv"
  val_label: "data/pretrain/ISIC_2016_test.csv"
  num_workers: 10
  debug_transform: True
optimizer:
  name: "sgd"
  batch_size: 512
  lr: 0.01
  weight_decay: 0
scheduler:
  name: step
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# pytorch-lightning trainer params
max_epochs: 100
devices: [2]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
log_every_n_steps: 25