defaults:
  - _self_
  - wandb: private.yaml
  - augmentations: linear.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-linear-isic2017"
finetune: False # perform finetune or linear-probbing
pretrain:
  method: "simclr"
  ckpt: "trained_models/simclr/44dhehnr/simclr-symmetric-512bs-44dhehnr-ep=99.ckpt"
  ckpt_key: "backbone"
backbone:
  name: "resnet18"
loss_fn: 
  name: "ce" # choose from [ce, focal, label_smoothing_ce, soft_target_ce]
data:
  dataset: isic2017
  data_path: "data/pretrain/images"
  train_label: "data/pretrain/ISIC_2017_train.csv"
  val_label: "data/pretrain/ISIC_2017_test.csv"
  num_workers: 10
  debug_transform: True
optimizer:
  name: "sgd"
  batch_size: 512
  lr: 0.01
  weight_decay: 0
scheduler:
  name: step
  lr_decay_steps: [30, 40]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# pytorch-lightning trainer params
max_epochs: 50
devices: [1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
log_every_n_steps: 2