defaults:
  - _self_
  - wandb: private.yaml
  - augmentations: finetune.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "moby-fintune-isic2018"
finetune: True # perform finetune or linear-probbing
pretrain:
  method: "moby"
  # ckpt: "trained_models/moby/gmiv3reu/moby-run1-gmiv3reu-ep=99.ckpt" # pretrain ckpt
  ckpt: "trained_models/moby/0bbqcp0a/moby-symmetric-0bbqcp0a-ep=99.ckpt"
  ckpt_key: "momentum_backbone"
backbone:
  name: "resnet18"
loss_fn: 
  name: "ce" # choose from [ce, focal, label_smoothing_ce, soft_target_ce]
data:
  dataset: isic2018
  data_path: "data/pretrain/images"
  train_label: "data/pretrain/ISIC_2018_train.csv"
  val_label: "data/pretrain/ISIC_2018_test.csv"
  num_workers: 10
  debug_transform: True
optimizer:
  name: "sgd"
  batch_size: 512
  lr: 0.01
  weight_decay: 0
scheduler:
  name: step
  lr_decay_steps: [30, 40]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False


# pytorch-lightning trainer params
max_epochs: 50
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
log_every_n_steps: 2