defaults:
  - _self_
  - wandb: private.yaml
  - augmentations: finetune.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov2plus-isicarchive-finetune"
finetune: True # perform finetune or linear-probbing
pretrain:
  method: "mocov2plus"
  ckpt: "trained_models/mocov2plus/bp5i1erd/mocov2plus-bp5i1erd-ep=99.ckpt" # pretrain ckpt
  # ckpt: "trained_models/mocov2plus/sbyhf7s3/mocov2plus-sbyhf7s3-ep=64.ckpt" # pretrain ckpt
  ckpt_key: "momentum_backbone" #ckpt key in ["backbone", "momentum_backbone"]
backbone:
  name: "resnet18"
loss_fn: 
  name: "ce" # choose from [ce, focal, label_smoothing_ce, soft_target_ce]
data:
  dataset: isic2016
  data_path: "data/pretrain/images"
  train_label: "data/pretrain/ISIC_2016_train.csv"
  val_label: "data/pretrain/ISIC_2016_test.csv"
  num_workers: 8
  debug_transform: True
optimizer:
  name: "sgd"
  batch_size: 512
  lr: 0.0001
  weight_decay: 5e-5
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# pytorch-lightning trainer params
max_epochs: 25
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
log_every_n_steps: 2