defaults:
  - _self_
  - wandb: private.yaml
  - augmentations: finetune.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "nsmoco-fintune-isic201"
finetune: True # perform finetune or linear-probbing
pretrain:
  method: "nsmoco" 
  ckpt: "trained_models/nsmoco/cna7qk9e/nsmoco-symmetric-cna7qk9e-ep=99.ckpt" # tau = 0.2
  # ckpt: "trained_models/nsmoco/lg1hhc97/nsmoco-symmetric-lg1hhc97-ep=99.ckpt" # tau = 0.1
  ckpt_key: "momentum_backbone"
backbone:
  name: "resnet18"
loss_fn: 
  name: "ce" # choose from [ce, focal, label_smoothing_ce, soft_target_ce]
data:
  dataset: isic2016
  data_path: "data/pretrain/images"
  train_label: "data/pretrain/ISIC_2016_train.csv"
  val_label: "data/pretrain/ISIC_2016_test.csv"
  num_workers: 10
  debug_transform: True
optimizer:
  name: "sgd"
  batch_size: 512
  lr: 0.01
  weight_decay: 0
scheduler:
  name: step
  lr_decay_steps: [30, 40]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True


# pytorch-lightning trainer params
max_epochs: 50
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
log_every_n_steps: 2