defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-symmetric"
method: "byol"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: isic_archive
  train_path: ./data/pretrain/images
  num_workers: 10
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.25
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
  interval: "step"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True


# overwrite PL stuff
max_epochs: 100
devices: [2]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
