defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "dino-run3"
method: "dino"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 4096
  clip_grad: 0
  freeze_last_layer: 1 # epochs to freeze prototype layer
  use_bn_in_head: False 
  norm_last_layer: True # whether normalize the the param of prototype layer
  student_temperature: 0.1
  warmup_teacher_temperature: 0.04
  teacher_temperature: 0.07 # linear increase from [warmup_teacher_temperature -> teacher_temperature]
  warmup_teacher_temperature_epochs: 30 # epochs to increase
momentum:
  base_tau: 0.996
  final_tau: 1.0
data:
  dataset: isic_archive
  train_path: ./data/pretrain/images
  num_workers: 16
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.2
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
