defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr"
method: "simclr"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 512
  temperature: 0.2
backbone:
  name: "resnet18"
data:
  dataset: isic_archive
  train_path: ./data/pretrain/images
  num_workers: 16
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.2
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True


# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16