defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simsiam-symmetric"
method: "simsiam"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  pred_hidden_dim: 512
  temperature: 0.2
backbone:
  name: "resnet18"
data:
  dataset: isic_archive
  train_path: ./data/pretrain/images
  num_workers: 10
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.5
  weight_decay: 1e-5
scheduler:
  name: "warmup_cosine"
  interval: "step"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
