- rrc:
    enabled: True
    crop_min_scale: 0.2
    crop_max_scale: 1.0
  horizontal_flip:
    prob: 0.5
  crop_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

- rrc:
    enabled: False
  horizontal_flip:
    prob: 0.
  resize_size: 256
  crop_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]